Corrected indentation.

diff --git a/install-pjb-environment b/install-pjb-environment
--- a/install-pjb-environment
+++ b/install-pjb-environment
@@ -172,24 +172,24 @@ function unarchive(){
     local dir="$2"
     case "${archive}" in
 	(*.tar.bz2)
-            rm -rf  "${dir}"
+        rm -rf  "${dir}"
 	    printi 'Extracting ' "${archive}"
-            tar jxf "${archive}"
-            ;;
+        tar jxf "${archive}"
+        ;;
 	(*.tar.gz|*.tgz)
-            rm -rf  "${dir}"
+        rm -rf  "${dir}"
 	    printi 'Extracting ' "${archive}"
-            tar zxf "${archive}"
-            ;;
+        tar zxf "${archive}"
+        ;;
 	(*.zip)
-            rm -rf  "${dir}"
+        rm -rf  "${dir}"
 	    printi 'Extracting ' "${archive}"
-            unzip "${archive}"
-            ;;
+        unzip "${archive}"
+        ;;
 	(*)
-            printe "Unknown archive type: ${archive}"
-            exit 1
-            ;;
+        printe "Unknown archive type: ${archive}"
+        exit 1
+        ;;
     esac
 }
 
@@ -279,7 +279,7 @@ function install_pjb_environment(){
     mkdir -p src/public
     cd src/public
     for repo in "${repositories[@]}" ; do
-	git-clone-or-warn "${repo}"
+	    git-clone-or-warn "${repo}"
     done
     cd "$HOME"
     link src/public/bin bin
@@ -313,10 +313,10 @@ function install_emacs_from_sources(){
         local url='ftp://ftp.gnu.org/gnu/emacs/emacs-25.1.tar.gz'
         local tarball;tarball="$(basename "${url}")"
         local dir    ;dir="$(basename "${tarball}" .tar.gz)"
-	if [[ ! -e "${tarball}" ]] ; then
+	    if [[ ! -e "${tarball}" ]] ; then
             download "${url}"
             download "${url}.sig"
-	fi
+	    fi
         unarchive "${tarball}" "${dir}"
         cd "${dir}"
         compile "${dir}" "$(pwd)" --with-x --without-ns --with-gif=no
@@ -351,12 +351,11 @@ function install_ccl_from_sources(){
 
 function install_clisp_from_sources(){
     cd "${PREFIX}"/src/
-    local do_ffi=false
+    local do_ffi=true
     local hyperspec='http://www.lispworks.com/documentation/HyperSpec/'
     local url='http://hg.code.sf.net/p/clisp/clisp'
     local dir='clisp'
     local logbase;logbase="/usr/local/src/${dir}"
-    cd /usr/local/src/
     if [ ! -e "${dir}" ] ; then
         hg clone "${url}" "${dir}"
     fi
@@ -367,9 +366,9 @@ function install_clisp_from_sources(){
         --prefix="${PREFIX}"
 
         --with-threads=POSIX_THREADS
-	--with-dynamic-modules
-	--with-unicode
-	--with-readline
+	    --with-dynamic-modules
+	    --with-unicode
+	    --with-readline
 
         --with-module=berkeley-db
         --with-module=clx/new-clx
@@ -378,13 +377,13 @@ function install_clisp_from_sources(){
         --with-module=queens
         --with-module=rawsock
 
-	--with-libsigsegv-prefix=/opt/local/lib
-	--with-libpth-prefix=/opt/local/lib
-	--with-libiconv-prefix=/opt/local/lib
-	--with-libintl-prefix=/opt/local/lib
-	--with-libffcall-prefix=/opt/local/lib
-	--with-libtermcap-prefix=/opt/local/lib
-	--with-libreadline-prefix=/opt/local/lib
+	    --with-libsigsegv-prefix=/opt/local/lib
+	    --with-libpth-prefix=/opt/local/lib
+	    --with-libiconv-prefix=/opt/local/lib
+	    --with-libintl-prefix=/opt/local/lib
+	    --with-libffcall-prefix=/opt/local/lib
+	    --with-libtermcap-prefix=/opt/local/lib
+	    --with-libreadline-prefix=/opt/local/lib
 
         --hyperspec="${hyperspec}"
     )
@@ -447,7 +446,7 @@ function install_abcl_from_sources(){
     local logbase;logbase="$(pwd)/${dir}"
     export JAVA_HOME="${jdkhome}"
     if [[ ! -e  "${tarball}" ]] ; then
-	download "${url}"
+	    download "${url}"
     fi
     unarchive "${tarball}" "${dir}"
     cd "${dir}"
@@ -570,15 +569,15 @@ function install_emacsformacosx(){
         printw 'There is already an item named ' "${dir}" ','
         printw '         skipping downloading emacsformacosx '  "${url}"
     else
-	local dmg;dmg="$(basename "${url}")"
-	local mnt;mnt="$(mktemp -d /tmp/mnt.XXXXXX)" || ( printe cannot make mount point ; return 1 )
-	cd /tmp
-	download "${url}"
-	printi 'Installing emacsformacosx'
-	dev="$(hdiutil attach "${dmg}" -mountpoint "${mnt}" |grep dev|tail -1|awk '{print $1}')"
-	cp -av "${mnt}"/Emacs.app "${dir}"
-	hdiutil detach "${dev}"
-	rmdir "${mnt}"
+	    local dmg;dmg="$(basename "${url}")"
+	    local mnt;mnt="$(mktemp -d /tmp/mnt.XXXXXX)" || ( printe cannot make mount point ; return 1 )
+	    cd /tmp
+	    download "${url}"
+	    printi 'Installing emacsformacosx'
+	    dev="$(hdiutil attach "${dmg}" -mountpoint "${mnt}" |grep dev|tail -1|awk '{print $1}')"
+	    cp -av "${mnt}"/Emacs.app "${dir}"
+	    hdiutil detach "${dev}"
+	    rmdir "${mnt}"
     fi
 }
 
@@ -606,25 +605,25 @@ function install_macports(){
         printw 'There is already an item named ' "${item}" ','
         printw '         skipping installing MacPorts.'
     else
-	local ignore1
-	local ignore2
-	local version
-	local url
-	read ignore1 ignore2 version <<<$(distribution)
-	case "${version}" in
+	    local ignore1
+	    local ignore2
+	    local version
+	    local url
+	    read ignore1 ignore2 version <<<$(distribution)
+	    case "${version}" in
 	    (16.*)  url='https://distfiles.macports.org/MacPorts/MacPorts-2.3.4-10.12-Sierra.pkg' ;;
 	    (15.*)  url='https://distfiles.macports.org/MacPorts/MacPorts-2.3.4-10.11-ElCapitan.pkg' ;;
 	    (14.*)  url='https://distfiles.macports.org/MacPorts/MacPorts-2.3.4-10.10-Yosemite.pkg' ;;
 	    (13.*)  url='https://distfiles.macports.org/MacPorts/MacPorts-2.3.4-10.9-Mavericks.pkg' ;;
 	    (*) printe 'Unexpected OSX version:' "${version}"
-		return 1
-		;;
-	esac
-	cd /tmp
-	local packageName="$(basename "${url}")"
-	download "${url}"
-	printi 'Installing' "${packageName}"
-	sudo installer -pkg "${packageName}" -target /
+		    return 1
+		    ;;
+	    esac
+	    cd /tmp
+	    local packageName="$(basename "${url}")"
+	    download "${url}"
+	    printi 'Installing' "${packageName}"
+	    sudo installer -pkg "${packageName}" -target /
     fi
 }
 
@@ -684,8 +683,8 @@ function post_install_ports(){
 function install_all(){
 
     case "$(uname)" in
-    	(Linux)
-    	    if [ -r /etc/os-release ] ; then
+    (Linux)
+    	if [ -r /etc/os-release ] ; then
     		if grep -q -s -e '^ID=debian' /etc/os-release ; then
     		    # Debian
     		    install_apt_packages "${debian_packages[@]}"
@@ -693,15 +692,15 @@ function install_all(){
     		    # Debian
     		    install_apt_packages "${ubuntu_packages[@]}"
     		fi
-    	    fi
-    	    ;;
-    	(Darwin)
-            install_emacsformacosx
-            install_macports
-    	    export "PATH=/opt/local/bin:$PATH"
-    	    sudo "${self}" --install-ports
-    	    post_install_ports
-            ;;
+    	fi
+    	;;
+    (Darwin)
+        install_emacsformacosx
+        install_macports
+    	export "PATH=/opt/local/bin:$PATH"
+    	sudo "${self}" --install-ports
+    	post_install_ports
+        ;;
     esac
 
     install_pjb_environment
@@ -721,17 +720,17 @@ function usage(){
 
 function main(){
     for arg ; do
-	case "${arg}" in
+	    case "${arg}" in
 	    (--install-ports)
-		install_ports
-		exit 0
-		;;
+		    install_ports
+		    exit 0
+		    ;;
 	    (*)
-		printf 'Invalid option %s\n' "${arg}"
-		usage "$(basename "$0")"
-		exit 1
-		;;
-	esac
+		    printf 'Invalid option %s\n' "${arg}"
+		    usage "$(basename "$0")"
+		    exit 1
+		    ;;
+	    esac
     done
     install_all
     exit 0
@@ -739,3 +738,4 @@ function main(){
 
 
 main "$@"
+#set +eu
